files:
  - source: /src/language/en.json
    translation: /src/language/%language%.json
    languages_mapping:
      language:
        ru: ru
        ja: ja
        zh-CN: zh_Hans
        zh-TW: zh_Hant
        ko: ko
  - source: /src/terms/en-US.md
    translation: /src/terms/%language%.md
    languages_mapping:
      language:
        ru: ru-RU
        ja: ja-JP
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        ko: ko-KR
